apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: rootshells.root.shell
spec:
  scope: Namespaced
  group: root.shell
  versions:
    - name: v1
      served: true
      storage: true
  names:
    kind: RootShell
    plural: rootshells
    singular: rootshell
    shortNames:
      - rshell
      - nshell
  additionalPrinterColumns:
    - name: hostnode
      type: string
      priority: 0
      JSONPath: .spec.hostnode
      description: Hostname of Root Shell
